name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "rand.sobczak@gmail.com"
          git config --global user.name "Rand"
          git remote add space https://huggingface.co/spaces/sobcza11/huggingface_demo
          git push https://sobcza11:${HF_TOKEN}@huggingface.co/spaces/sobcza11/huggingface_demo main
